version: '3.8'

services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgrespassword}'
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    depends_on:
      - 'postgres'
    restart: always
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET:?HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE:?HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE:-anonymous}
  hasura-backend-plus:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - 'graphql-engine'
      - 'minio'
    ports:
      - '3100:3000'
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET:?HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID:-minio_access_key}'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      AUTO_MIGRATE: '${AUTO_MIGRATE:?AUTO_MIGRATE}'
      GOOGLE_ENABLE: '${GOOGLE_ENABLE:?GOOGLE_ENABLE}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET : '${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET}'
      PROVIDER_SUCCESS_REDIRECT : '${PROVIDER_SUCCESS_REDIRECT:?PROVIDER_SUCCESS_REDIRECT}'
      COOKIE_SECRET: '${COOKIE_SECRET:?COOKIE_SECRET}'
  minio:
    image: minio/minio
    restart: always
    volumes:
      - 'minio_data:/data'
    env_file: .env  
    environment:
      S3_BUCKET: '${S3_BUCKET:-hasura-backend-plus}'
      MINIO_ACCESS_KEY: '${S3_ACCESS_KEY_ID:-minio_access_key}' ## min 8 character
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}' ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/$${S3_BUCKET:-hasura-backend-plus} && /usr/bin/minio server /export'"
volumes:
  db_data:
  minio_data:
